name: Update Stargazers World Map

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: profile/stargazers-worldmap.svg
          token: ${{ secrets.README_STATS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts: no
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
          plugin_stargazers_worldmap_sample: 200
