name: Update Stargazers World Map

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: lowlighter/metrics@latest
        with:
          filename: profile/stargazers-worldmap.svg
          token: ${{ secrets.README_STATS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts: no
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
          plugin_stargazers_worldmap_sample: 200

      - name: Remove map headings
        run: |
          perl -0pi -e '
            s{<h2 class="field">.*?</h2>}{}gs;
            s{<h3 class="margin-lr-auto">Stargazers origins</h3>}{}gs;
            s{<svg xmlns="http://www\.w3\.org/2000/svg" width="480" height="436" class="">}{<svg xmlns="http://www.w3.org/2000/svg" width="480" height="315" viewBox="0 0 480 315" class="">}s;
            s{\.margin-bottom\{margin-bottom:16px\}}{.margin-bottom{margin-bottom:0}}s;
            s{<div xmlns="http://www\.w3\.org/1999/xhtml" id="metrics-end"></div>}{}s;
          ' profile/stargazers-worldmap.svg

      - name: Commit map if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/stargazers-worldmap.svg
          git diff --cached --quiet && exit 0
          git commit -m "chore: update stargazers world map"
          git push
